### PR TITLE
Protected content option

### PR DESCRIPTION
**Pull request by djdeath**
Just checking our protected content support work on Anv : https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8064

### CODE REVIEW

**Comment by krh** [comment]
Cool, looks good.

**Comment by djdeath** [comment]
@krh : Are you okay with me merging it? :)

**Comment by krh** [comment]
Sorry, thought I did.

**Comment by krh** [comment]
But yes, that would've fine :)

**Pull request merged**
